POST http://localhost:3001/api/v1/persons
Content-Type: application/json

{
    "number": "045-2345678"
}

###
POST http://localhost:3001/api/v1/persons
Content-Type: application/json

{
    "name": "John Doe"
}

###
POST http://localhost:3001/api/v1/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "145-2345678"
}

###
POST http://localhost:3001/api/v1/persons
Content-Type: application/json

{
    "name": "Anna",
    "number": "040-1234556"
}